apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: pulsar-console-api
  labels:
    app.kubernetes.io/name: pulsar-console
    app.kubernetes.io/component: api
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: ghcr.io/leonmeijer/pulsar-console-api:latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: pulsar-console-frontend
  labels:
    app.kubernetes.io/name: pulsar-console
    app.kubernetes.io/component: frontend
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: ghcr.io/leonmeijer/pulsar-console-frontend:latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local
